# Generated by Django 2.2.12 on 2020-05-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200502_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private')], default='Public', max_length=50, verbose_name='who can see this album'),
        ),
    ]
